### ISSUE TITLE
No Python 3.6 support with SciPy 1.6

### ISSUE THREAD

**Issue by Dobatymo** [stephenhky/PyShortTextCategorization#111]
SciPy 1.6.0 drops Python 3.6 support <https://scipy.github.io/devdocs/release.1.6.0.html>
So maybe `scipy<1.6.0` should be specified in the `requirements.txt` and `setup_requirements.txt` files.

**Comment by stephenhky** [comment]
Thanks for the note.
`shorttext` requires only `scipy>=1.2.0`. If it is installed in Python 3.6, it will get the latest scipy package available for Python 3.6 when it is installed using `pip`. No change in requirement files are necessary.

**Comment by Dobatymo** [comment]
Have you actually verified that?
Because I get with python 3.6.9 on ubuntu
```root:~$ python3 -m pip install shorttext
Collecting shorttext
  Downloading shorttext-1.4.3.tar.gz (257 kB)
     |████████████████████████████████| 257 kB 1.2 MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7ip2smbm/shorttext_620e5debf2f040568acaa2bca80b3d80/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7ip2smbm/shorttext_620e5debf2f040568acaa2bca80b3d80/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_jktbuco
         cwd: /tmp/pip-install-7ip2smbm/shorttext_620e5debf2f040568acaa2bca80b3d80/
    Complete output (76 lines):
    Compiling shorttext/metrics/dynprog/dldist.pyx because it depends on /home/root/.local/lib/python3.6/site-packages/numpy/__init__.pxd.
    Compiling shorttext/metrics/dynprog/lcp.pyx because it depends on /home/root/.local/lib/python3.6/site-packages/numpy/__init__.pxd.
    [1/2] Cythonizing shorttext/metrics/dynprog/dldist.pyx
    [2/2] Cythonizing shorttext/metrics/dynprog/lcp.pyx
    /home/root/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-7ip2smbm/shorttext_620e5debf2f040568acaa2bca80b3d80/shorttext/metrics/dynprog/dldist.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    /home/root/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-7ip2smbm/shorttext_620e5debf2f040568acaa2bca80b3d80/shorttext/metrics/dynprog/lcp.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    Traceback (most recent call last):
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-9wvckf6u/scipy-1.6.0rc1/setup.py", line 31, in <module>
        return [package_string.strip() for package_string in open('test_requirements.txt', 'r')]
    RuntimeError: Python version >= 3.7 required.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7ip2smbm/shorttext_620e5debf2f040568acaa2bca80b3d80/setup.py", line 96, in <module>
        zip_safe=False)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/dist.py", line 719, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/root/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/root/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/root/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/root/.local/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-9wvckf6u/scipy-1.6.0rc1/setup.py", line 31, in <module>
        return [package_string.strip() for package_string in open('test_requirements.txt', 'r')]
    RuntimeError: Python version >= 3.7 required.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```

**Comment by stephenhky** [comment]
Sorry you are right.
I do not want to impose backward requirements as we are supposed to support more recent versions as always.
I will try to figure out how to specifically impose that for Python 3.6.

**Comment by stephenhky** [comment]
There is a release 1.4.4 which fixes this problem. However, it is advised to have a scipy installed already on your environment with python 3.6 first before installing shorttext 1.4.4.
