### ISSUE TITLE
py36requirements.txt is not included in source tar.gz

### ISSUE THREAD

**Issue by Dobatymo** [stephenhky/PyShortTextCategorization#117]
pip install fails on python 3.6 because `py36requirements.txt` is not included in the source distribution.

```
#12 74.96     ERROR: Command errored out with exit status 1:
#12 74.96      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7zctnz3x/shorttext_3f3465f496dd4418921e425c6accdec6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7zctnz3x/shorttext_3f3465f496dd4418921e425c6accdec6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0rba8bl7
#12 74.96          cwd: /tmp/pip-install-7zctnz3x/shorttext_3f3465f496dd4418921e425c6accdec6/
#12 74.96     Complete output (7 lines):
#12 74.96     Traceback (most recent call last):
#12 74.96       File "<string>", line 1, in <module>
#12 74.96       File "/tmp/pip-install-7zctnz3x/shorttext_3f3465f496dd4418921e425c6accdec6/setup.py", line 98, in <module>
#12 74.96         install_requires=install_requirements() if sys.version >= "3.7" else install_py36requirements(),
#12 74.96       File "/tmp/pip-install-7zctnz3x/shorttext_3f3465f496dd4418921e425c6accdec6/setup.py", line 30, in install_py36requirements
#12 74.96         return [package_string.strip() for package_string in open('py36requirements.txt', 'r')]
#12 74.96     FileNotFoundError: [Errno 2] No such file or directory: 'py36requirements.txt'
#12 74.96     ----------------------------------------
#12 74.96 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It should probably be added to the `MANIFEST.in` file.

**Comment by stephenhky** [comment]
The new release `1.4.6` has the problem addressed in the same way as suggested.
