### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by 424778940z** [stephenhky/PyShortTextCategorization#135]
Seems the script depends on numpy, but numpy is not listed as a dependency of this packege.
And I can confirm after install numpy, the package installs fine.
Could you fix the dependency?

```shell
(pyenv) PS E:\_downloader> pip install -U shorttext
Collecting shorttext
  Using cached shorttext-1.5.6.tar.gz (239 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\localadmin\AppData\Local\Temp\pip-install-_dka82ov\shorttext_5fe5e2c1949a4d48a9d03b438724d1df\setup.py", line 4, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by 424778940z** [comment]
Hummm, I checked requirements.txt, it has `numpy>=1.16.0` in it, not sure why pip won't install it

**Comment by stephenhky** [comment]
What is happening is that `setup.py` actually require `numpy` to be pre-installed. I think I got a solution to it. I will test it today and made a PR.
