### ISSUE TITLE
A Console Scripts question

### ISSUE THREAD

**Issue by zyssyz123** [stephenhky/PyShortTextCategorization#30]
I got a trouble when I run shortTextCategorizerConsole,such as:
`ShortTextCategorizerConsole: error: too few arguments`
And then the program was interrupted by Compiler.

Thanks for your assistance.

**Comment by stephenhky** [comment]
What arguments did you put? Maybe you can show how you run from the command prompt and the full error msg.

**Comment by zyssyz123** [comment]
I figure out that ,Thank you so much.
But I got in a new trouble when I use the test case named 'test_var_nn_embedded_vec_classifier'.
```
sh: wget: command not found
mv: rename test_w2v_model.bin?raw=true to test_w2v_model.bin: No such file or directory
Esh: wget: command not found
mv: rename test_w2v_model.bin?raw=true to test_w2v_model.bin: No such file or directory
Esh: wget: command not found
mv: rename test_w2v_model.bin?raw=true to test_w2v_model.bin: No such file or directory
E
======================================================================
ERROR: testCLSTMWordEmbedWithoutGensim (__main__.TestVarNNEmbeddedVecClassifier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/songgeshuai/Downloads/PyShortTextCategorization-master/test/test_var_nn_embedded_vec_classifier.py", line 14, in setUp
    self.w2v_model = shorttext.utils.load_word2vec_model("test_w2v_model.bin", binary=True)  # load word2vec model
  File "/Users/songgeshuai/Downloads/PyShortTextCategorization-master/shorttext/utils/wordembed.py", line 20, in load_word2vec_model
    return KeyedVectors.load_word2vec_format(path, binary=binary)
  File "/Users/songgeshuai/Library/Python/2.7/lib/python/site-packages/gensim/models/keyedvectors.py", line 1119, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/Users/songgeshuai/Library/Python/2.7/lib/python/site-packages/gensim/models/utils_any2vec.py", line 173, in _load_word2vec_format
    with utils.smart_open(fname) as fin:
  File "/Users/songgeshuai/Library/Python/2.7/lib/python/site-packages/smart_open/smart_open_lib.py", line 176, in smart_open
    return file_smart_open(parsed_uri.uri_path, mode, encoding=encoding, errors=errors)
  File "/Users/songgeshuai/Library/Python/2.7/lib/python/site-packages/smart_open/smart_open_lib.py", line 671, in file_smart_open
    raw_fobj = open(fname, raw_mode)
IOError: [Errno 2] No such file or directory: 'test_w2v_model.bin'
```
Did I forget some package?

**Comment by stephenhky** [comment]
It is not your problem.

The test was designed to run on travis CI, which has the Unix system with command "wget". However, a lot of local machines do not have this command.

I can rewrite that part of the test so that it can run in all systems.

**Comment by stephenhky** [comment]
I rewrote the unit test. please check it out.
